package com.xh.dal.postgres.model;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blog_text
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String blogText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.ext_info
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blog_text
     *
     * @return the value of blog.blog_text
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getBlogText() {
        return blogText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blog_text
     *
     * @param blogText the value for blog.blog_text
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setBlogText(String blogText) {
        this.blogText = blogText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.ext_info
     *
     * @return the value of blog.ext_info
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.ext_info
     *
     * @param extInfo the value for blog.ext_info
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.gmt_create
     *
     * @return the value of blog.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.gmt_create
     *
     * @param gmtCreate the value for blog.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.gmt_modified
     *
     * @return the value of blog.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.gmt_modified
     *
     * @param gmtModified the value for blog.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.user_id
     *
     * @return the value of blog.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.user_id
     *
     * @param userId the value for blog.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.status
     *
     * @return the value of blog.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.status
     *
     * @param status the value for blog.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}