package com.xh.dal.postgres.model;

import java.util.Date;

public class UserCredential {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.credential_type
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String credentialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.credential_value
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private String credentialValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credential.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.id
     *
     * @return the value of user_credential.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.id
     *
     * @param id the value for user_credential.id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.gmt_create
     *
     * @return the value of user_credential.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.gmt_create
     *
     * @param gmtCreate the value for user_credential.gmt_create
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.gmt_modified
     *
     * @return the value of user_credential.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.gmt_modified
     *
     * @param gmtModified the value for user_credential.gmt_modified
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.user_id
     *
     * @return the value of user_credential.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.user_id
     *
     * @param userId the value for user_credential.user_id
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.credential_type
     *
     * @return the value of user_credential.credential_type
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getCredentialType() {
        return credentialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.credential_type
     *
     * @param credentialType the value for user_credential.credential_type
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setCredentialType(String credentialType) {
        this.credentialType = credentialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.credential_value
     *
     * @return the value of user_credential.credential_value
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public String getCredentialValue() {
        return credentialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.credential_value
     *
     * @param credentialValue the value for user_credential.credential_value
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setCredentialValue(String credentialValue) {
        this.credentialValue = credentialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credential.status
     *
     * @return the value of user_credential.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credential.status
     *
     * @param status the value for user_credential.status
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}