package com.xh.dal.postgres.mapper;

import com.xh.dal.postgres.model.Blog;
import com.xh.dal.postgres.model.BlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int insert(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int insertSelective(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    Blog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByExampleSelective(@Param("row") Blog row, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByExample(@Param("row") Blog row, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByPrimaryKeySelective(Blog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByPrimaryKey(Blog row);

    /**
     * 查询示例（不包含BLOB字段）
     */
    List<Blog> selectByExampleWithoutBlobs(BlogExample example);

    /**
     * 根据主键查询（不包含BLOB字段）
     */
    Blog selectByPrimaryKeyWithoutBlobs(Integer id);
}