package com.xh.dal.postgres.mapper;

import com.xh.dal.postgres.model.UserCredential;
import com.xh.dal.postgres.model.UserCredentialExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserCredentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    long countByExample(UserCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int deleteByExample(UserCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int insert(UserCredential row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int insertSelective(UserCredential row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    List<UserCredential> selectByExample(UserCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    UserCredential selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByExampleSelective(@Param("row") UserCredential row, @Param("example") UserCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByExample(@Param("row") UserCredential row, @Param("example") UserCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByPrimaryKeySelective(UserCredential row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credential
     *
     * @mbg.generated Fri Nov 28 12:11:28 CST 2025
     */
    int updateByPrimaryKey(UserCredential row);
}